"""Initial Migration

Revision ID: 82026cdb3f78
Revises: f53df272ef0d
Create Date: 2022-05-19 23:30:37.862111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82026cdb3f78'
down_revision = 'f53df272ef0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
